### ISSUE TITLE
Export to elasticsearch - Logger version 3.18 from all tools

### ISSUE THREAD

**Issue by dinosn** [nccgroup/LoggerPlusPlus#105]
**Description:**
Exported logs are coming only from proxy tool, not from all tools

Also during testing stop / start on the Elastic Exporter seem not to be actually working.  At least no messages are send towards the ELK where logs are visible on the 'View Logs ' tab.

**Steps To Reproduce: **
Configure and send to kibana 7.7.0

**Expected behavior:**
Logs from all tools (repeater/scanner/ to be visible on kibana

**Version:**
Logger version 3.18 to Kibana 7.7.0

**Comment by CoreyD97** [comment]
Are you seeing requests from other tools in the log view window of Logger++? Or do they not show there either?

**Comment by CoreyD97** [comment]
> Also during testing stop / start on the Elastic Exporter seem not to be actually working. At least no messages are send towards the ELK where logs are visible on the 'View Logs ' tab.

Sorry, I'm not sure what you mean by this. Does the elastic exporter not work at all? Or do you mean because you can't see any  requests made to the elastic api in Logger?

**Comment by dinosn** [comment]
Hi, sorry for the confusion let me write the full case.  For a start i'm running 2 instances of Burp proxy with Logger++ enabled on both for elastic search log shipping. Both on the same system.  

I don't think that this is of an issue i'm adding it just to give the full view of the setup.

1. On logger++ at Burp, there is no problem at all, I can see all requests from all tools passing through.
2. On the elasticsearch I could see only the requests from the Proxy, at the first time that I enabled it.
3. By doing a stop on the Elastic Exporter and a start again, I receive nothing further from that point onwards to ELK.
4. Elastic exporter is set with all fields enabled.

PS: I'm using a small docker setup as I wanted to test the functionality based on https://hub.docker.com/r/nshou/elasticsearch-kibana/

**Comment by CoreyD97** [comment]
Hmm, could you give [this](https://github.com/nccgroup/LoggerPlusPlus/suites/775557964/artifacts/8133708) version a try and let me know if you're still seeing the same issue?

**Comment by dinosn** [comment]
Hi, 

 Yes I'm afraid I see the same case.   I will change my ELK setup soon and test again. I notice that prefered is kibana 6 ( from past issues that I read here ), so I will adapt to that from my end. 

I also see on the console the following errors:

```
java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.net.URL
at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:833)
at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:804)
at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:789)
at com.nccgroup.loggerplusplus.exports.ElasticExporter.buildIndexRequest(ElasticExporter.java:124)
at com.nccgroup.loggerplusplus.exports.ElasticExporter.indexPendingEntries(ElasticExporter.java:145)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.net.URL
at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:833)
at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:804)
at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:789)
at com.nccgroup.loggerplusplus.exports.ElasticExporter.buildIndexRequest(ElasticExporter.java:124)
at com.nccgroup.loggerplusplus.exports.ElasticExporter.indexPendingEntries(ElasticExporter.java:145)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by CoreyD97** [comment]
Ah, thanks for that stack trace! I see the issue here. I'll get that sorted now.

**Comment by dinosn** [comment]
Thank you very much !

**Comment by CoreyD97** [comment]
Hey @dinosn!

Really sorry for the long delay, I've been on a couple of busy jobs recently. I've just pushed a fix that should solve requests from other tools not being uploaded to elasticsearch and will include it in the next release. You can download the jar from [here](https://github.com/nccgroup/LoggerPlusPlus/suites/960822390/artifacts/12079650) if you want to give it a try in the meantime.

**Comment by dinosn** [comment]
Hi mate, thanks for the update I will give it a try!
