### ISSUE TITLE
Getting Nullpointer Exception while loading Loggerplusplus.jar in burpsuite

### ISSUE THREAD

**Issue by bharathyakasi** [nccgroup/LoggerPlusPlus#135]
*java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.google.gson.Gson.fromJson(String, java.lang.Class)" is null
	at com.nccgroup.loggerplusplus.logging.LoggingController.configureLogger(LoggingController.java:32)
	at com.nccgroup.loggerplusplus.logging.LoggingController.<init>(LoggingController.java:25)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.d3n.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.google.gson.Gson.fromJson(String, java.lang.Class)" is null
	at com.nccgroup.loggerplusplus.logging.LoggingController.configureLogger(LoggingController.java:32)
	at com.nccgroup.loggerplusplus.logging.LoggingController.<init>(LoggingController.java:25)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.d3n.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)*Description:**

**Steps To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Version:**

**Comment by CoreyD97** [comment]
Can you share the version number you're using please?

**Comment by bharathyakasi** [comment]
burpsuiteprofesssionalv2021.5.2

**Comment by CoreyD97** [comment]
Thanks, and which version of Logger++?

**Comment by bharathyakasi** [comment]
the latest one where there is a provision of Basic, APIkey authentication

**Comment by bharathyakasi** [comment]
its working for some of our team members and some people are getting Nullpointer Exception

**Comment by CoreyD97** [comment]
Could you give this version a try and let me know if you still have the issue?
https://github.com/nccgroup/LoggerPlusPlus/releases/tag/v3.19.1

**Comment by bharathyakasi** [comment]
Thanks its working Now :)
