### ISSUE TITLE
Latest Burp Pro Early Adopter release breaks Logger++

### ISSUE THREAD

**Issue by aroly** [nccgroup/LoggerPlusPlus#149]
**Description:**

Latest Burp Pro Early Adopter release (v2022.3.3-12488) seems to break Logger++, it does not load properly anymore. I tried with the latest jar available on the "release" page of this repo (v3.19.3). 

**Steps To Reproduce:**

Try to load the extension.

**Expected behavior:**

Extension is loaded.

**Screenshots:**

Stacktrace is: 

```
java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @261689cc
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.nccgroup.loggerplusplus.preferences.LoggerPreferenceFactory.createDefaults(LoggerPreferenceFactory.java:42)
	at com.coreyd97.BurpExtenderUtilities.PreferenceFactory.buildPreferences(PreferenceFactory.java:31)
	at com.nccgroup.loggerplusplus.preferences.PreferencesController.<init>(PreferencesController.java:36)
	at com.nccgroup.loggerplusplus.LoggerPlusPlus.registerExtenderCallbacks(LoggerPlusPlus.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.fbn.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Version:**

v3.19.3

**Comment by aroly** [comment]
Burp Pro v2022.3.4-12540 is ok, Logger++ is loading correctly.

Closing the issue.

**Comment by tsc-awardle** [comment]
Adding the following launch parameters to a non-bundled JDK fixes this issue for me

```
"--add-opens" "java.desktop/java.awt=ALL-UNNAMED" "--add-opens" "java.desktop/java.awt.color=ALL-UNNAMED"
```

See the following answer on SF for more info https://stackoverflow.com/a/41265267
