### ISSUE TITLE
i cant intall loger+++  

### ISSUE THREAD

**Issue by khaldsalhi** [nccgroup/LoggerPlusPlus#187]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.l5y.k(Unknown Source)
	at burp.l5y.<init>(Unknown Source)
	at burp.sg1.Z(Unknown Source)
	at burp.lmh.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by C0DEbrained** [comment]
What version of Logger++ are you trying to use, and which Burp version are you running?

**Comment by khaldsalhi** [comment]
Version 3.20.0
I have downloaded in logerplus.jar and I have add in extension but error

**Comment by khaldsalhi** [comment]
Burp is version 2022.8.5

**Comment by C0DEbrained** [comment]
The newer versions of Logger++ will only work with Burp versions that support Montoya. I believe this is 2023 and later.

You'll either have to update your Burp or use a legacy version of Logger++.
