### ISSUE TITLE
v3.20.0 - Bug: Errors with Elastic Export

### ISSUE THREAD

**Issue by 303sec** [nccgroup/LoggerPlusPlus#197]
**Description:**

Looks like the elastic export functionality is broken, I've pasted the Java errors below that come up when pressing the 'Start Elastic Exporter' button

Burp - 2023.10.3.4
M2 Mac - MacOS 13.5.2 

Error:

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at com.nccgroup.loggerplusplus.exports.ElasticExporterControlPanel$2$1.done(ElasticExporterControlPanel.java:75)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at co.elastic.clients.json.jackson.JacksonJsonpMapper.<init>(JacksonJsonpMapper.java:56)
	at com.nccgroup.loggerplusplus.exports.ElasticExporter.setup(ElasticExporter.java:143)
	at com.nccgroup.loggerplusplus.exports.ExportController.enableExporter(ExportController.java:42)
	at com.nccgroup.loggerplusplus.exports.ElasticExporterControlPanel.enableExporter(ElasticExporterControlPanel.java:111)
	at com.nccgroup.loggerplusplus.exports.ElasticExporterControlPanel$2$1.doInBackground(ElasticExporterControlPanel.java:56)
	at com.nccgroup.loggerplusplus.exports.ElasticExporterControlPanel$2$1.doInBackground(ElasticExporterControlPanel.java:48)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	... 12 more
```

**Comment by C0DEbrained** [comment]
Hey!

This was broken for various reasons and is already tracked in #194.

If you need this functionality now please build from the dev branch 😊
