### ISSUE TITLE
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by ilatypov** [nccgroup/LoggerPlusPlus#89]
The following showed in stdout/stderr of the latest BURP Pro v.2020.1.2.
```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at loggerplusplus.userinterface.LoggerOptionsPanel.lambda$setComponentsActions$0(LoggerOptionsPanel.java:492)
	at javax.swing.JSpinner.fireStateChanged(JSpinner.java:458)
	at javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:386)
	at javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:119)
	at javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:447)
	at javax.swing.JSpinner.setValue(JSpinner.java:354)
	at javax.swing.JSpinner$DefaultEditor.propertyChange(JSpinner.java:752)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:798)
	at javax.swing.JFormattedTextField.commitEdit(JFormattedTextField.java:529)
	at javax.swing.JFormattedTextField$FocusLostHandler.run(JFormattedTextField.java:648)
	at javax.swing.JFormattedTextField.processFocusEvent(JFormattedTextField.java:630)
	at java.awt.Component.processEvent(Component.java:6295)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:689)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by CoreyD97** [comment]
Thanks for this, I believe this should be fixed in the upcoming version.

**Comment by ilatypov** [comment]
I installed the JAR compiled from here, and it works really well.  Thank you.
